# This is a basic workflow to help you get started with Actions

name: Nightly build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: none
  pull_request:
    branches: [ main, release/* ]
  schedule:
    - cron: "0 0 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  presetName: x64-Release&Test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    strategy:
      matrix:
        RunsOn: ['windows-latest', 'macOs-latest']
        
    # The type of runner that the job will run on
    runs-on: ${{matrix.RunsOn}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Git
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        
      - name: Install CMake
        # You may pin to the exact commit or the version.
        # uses: lukka/get-cmake@2e45cd82cd67abcfd1b61fb17c253b99f8257189
        uses: lukka/get-cmake@v3.21.2
        
      - name: Configure CMake project
        run: cmake --preset ${{ env.presetName }}
        
      - name: Build with CMake
        run: cmake --build $path
        env:
          path: 'out/build/${{ env.presetName }}'
      
      - name: Test
        run: ctest
